shared:
    image: node:14
    steps:
        - echo: echo "This PR job must not be executed on forked branch."

annotations:
    screwdriver.cd/restrictPR: fork

jobs:
    job1:
        requires: [ ~commit, ~pr ]

    job2:
        requires: [ ~commit, ~pr ]
